"""empty message

Revision ID: 066f35b58e44
Revises: d93f1577eeeb
Create Date: 2020-04-19 15:55:54.552111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "066f35b58e44"
down_revision = "d93f1577eeeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.String(length=255), nullable=True),
        sa.Column("remote_addr", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("request_logs")
    # ### end Alembic commands ###
