"""Add option to public recipe

Revision ID: 74dd49bc5c76
Revises: 6c2c2969ba4f
Create Date: 2019-09-25 21:51:09.365050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74dd49bc5c76"
down_revision = "6c2c2969ba4f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("is_public", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "is_public")
    # ### end Alembic commands ###
