"""empty message

Revision ID: 6c2c2969ba4f
Revises: 46c018428751
Create Date: 2019-08-01 07:47:18.742630

"""
from alembic import op
import sqlalchemy as sa

# from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "6c2c2969ba4f"
down_revision = "46c018428751"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "log_id",
        nullable=False,
        new_column_name="id",
        existing_type=sa.INTEGER(),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "logs",
        "id",
        nullable=False,
        new_column_name="log_id",
        existing_type=sa.INTEGER(),
    )
    # ### end Alembic commands ###
