"""Add recipe reactions

Revision ID: 0e33f7c6d78b
Revises: d45abe62b497
Create Date: 2020-10-22 23:02:01.024336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0e33f7c6d78b"
down_revision = "d45abe62b497"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_recipe_reactions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("recipe_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["recipe_id"], ["recipes.id"],),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_recipe_reactions_recipe_id"),
        "user_recipe_reactions",
        ["recipe_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_user_recipe_reactions_user_id"),
        "user_recipe_reactions",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    op.drop_table("user_recipe_reactions")
