"""empty message

Revision ID: 146d668cd04f
Revises: 066f35b58e44
Create Date: 2020-04-19 16:52:37.229937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "146d668cd04f"
down_revision = "066f35b58e44"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "request_logs", sa.Column("duration", sa.Float(precision=4), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("request_logs", "duration")
    # ### end Alembic commands ###
