"""Remove diet sizes

Revision ID: a8a0fbdf5043
Revises: f5d5e1df41f9
Create Date: 2020-05-06 10:23:39.974685

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "a8a0fbdf5043"
down_revision = "f5d5e1df41f9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("diets", "big_size")
    op.drop_column("diets", "small_size")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "diets", sa.Column("small_size", mysql.FLOAT(unsigned=True), nullable=False)
    )
    op.add_column(
        "diets", sa.Column("big_size", mysql.FLOAT(unsigned=True), nullable=False)
    )
    # ### end Alembic commands ###
