"""Add ratio to recipe

Revision ID: faddf34671a1
Revises: 0e33f7c6d78b
Create Date: 2020-11-09 21:51:51.689760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "faddf34671a1"
down_revision = "0e33f7c6d78b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("ratio", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "ratio")
    # ### end Alembic commands ###
