"""empty message

Revision ID: 118f7bcd451b
Revises: a59a5cc59698
Create Date: 2020-04-20 10:36:40.013089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "118f7bcd451b"
down_revision = "a59a5cc59698"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "view_count")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "recipes",
        sa.Column("view_count", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
