"""Add recipe description

Revision ID: d45abe62b497
Revises: 530497042e9d
Create Date: 2020-10-20 18:58:52.959422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d45abe62b497"
down_revision = "530497042e9d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("description", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "description")
    # ### end Alembic commands ###
