"""Add identification to request for items

Revision ID: a59a5cc59698
Revises: 146d668cd04f
Create Date: 2020-04-20 09:47:50.588002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a59a5cc59698"
down_revision = "146d668cd04f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("request_logs", sa.Column("item_id", sa.Integer(), nullable=True))
    op.add_column(
        "request_logs",
        sa.Column(
            "item_type", sa.Enum("user", "diet", "recipe", "ingredient"), nullable=True
        ),
    )
    op.alter_column(
        "request_logs",
        "user_id",
        existing_type=sa.String(length=255),
        type_=sa.Integer(),
        nullable=True,
    )
    op.create_index(
        op.f("ix_request_logs_user_id"), "request_logs", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "request_logs_ibfk_user_id", "request_logs", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("request_logs_ibfk_user_id", "request_logs", type_="foreignkey")
    op.drop_index(op.f("ix_request_logs_user_id"), table_name="request_logs")
    op.alter_column(
        "request_logs",
        "user_id",
        existing_type=sa.Integer(),
        type_=sa.String(length=255),
        nullable=True,
    )
    op.drop_column("request_logs", "item_type")
    op.drop_column("request_logs", "item_id")
    # ### end Alembic commands ###
