"""empty message

Revision ID: 2a3e83689c3d
Revises: fcffcb21448e
Create Date: 2020-04-01 20:17:50.626767

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "2a3e83689c3d"
down_revision = "fcffcb21448e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ingredients", sa.Column("is_approved", sa.Boolean(), nullable=True))
    op.add_column("ingredients", sa.Column("is_shared", sa.Boolean(), nullable=True))
    op.add_column(
        "ingredients", sa.Column("source", sa.String(length=255), nullable=True)
    )
    op.alter_column(
        "ingredients", "author", existing_type=mysql.VARCHAR(length=255), nullable=True
    )

    op.execute(
        """
        UPDATE
          ingredients
        SET
          ingredients.is_shared = 1,
          ingredients.is_approved = 1,
          ingredients.source = "user"
        WHERE
          ingredients.author = "basic"
          AND ingredients.is_shared IS NULL
        """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ingredients", "author", existing_type=mysql.VARCHAR(length=255), nullable=False
    )
    op.drop_column("ingredients", "source")
    op.drop_column("ingredients", "is_shared")
    op.drop_column("ingredients", "is_approved")
    # ### end Alembic commands ###
