"""empty message

Revision ID: acc249f30a78
Revises: dd3bd47bfbfd
Create Date: 2020-05-31 22:52:23.650839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "acc249f30a78"
down_revision = "dd3bd47bfbfd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_plan_has_recipes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
    )
    op.create_index(
        op.f("ix_daily_plan_has_recipes_recipes_id"),
        "daily_plan_has_recipes",
        ["recipes_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_daily_plan_has_recipes_recipes_id"),
        table_name="daily_plan_has_recipes",
    )
    op.drop_column("daily_plan_has_recipes", "id")
    # ### end Alembic commands ###
