"""empty message

Revision ID: cd8b44186600
Revises: d6fa11386771
Create Date: 2020-03-26 20:43:29.675447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd8b44186600"
down_revision = "d6fa11386771"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("diets", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_diets_user_id"), "diets", ["user_id"], unique=False)
    op.execute(
        """
        UPDATE
            diets
            LEFT JOIN users_has_diets AS UD ON
                UD.diet_id = diets.id
            LEFT JOIN users AS U ON
                U.id = UD.user_id
            SET diets.user_id = U.id
    """
    )
    op.create_foreign_key("fk_users", "diets", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users", "diets", type_="foreignkey")
    op.drop_index(op.f("ix_diets_user_id"), table_name="diets")
    op.drop_column("diets", "user_id")
    # ### end Alembic commands ###
