"""empty message

Revision ID: dd3bd47bfbfd
Revises: 9b90004a29a2
Create Date: 2020-05-31 22:19:05.227519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dd3bd47bfbfd"
down_revision = "9b90004a29a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("daily_plans", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_index(
        op.f("ix_daily_plans_user_id"), "daily_plans", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_daily_plan_users", "daily_plans", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_daily_plan_users", "daily_plans", type_="foreignkey")
    op.drop_index(op.f("ix_daily_plans_user_id"), table_name="daily_plans")
    op.drop_column("daily_plans", "user_id")
    # ### end Alembic commands ###
